routes/web.php
<?php

use App\School;
use App\Student;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/','schools');
Route::group(['as'=>'admin.','namespace'=>'Admin'],function(){
    Route::resource('schools','SchoolController');
    Route::resource('students','StudentController');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Student extends Model
{
    use SoftDeletes;

    protected $guarded = [];
    public static  function boot()
    {
        parent::boot();
        self::created(function($model){
            $students = $model->school->students->sortBy('name');
            $order = 1;
            $students->transform(function ($q)use(&$order){
                $q->order = $order;
                $q->save();
                ++$order;
            });
        });

        self::updated(function($model){
            $changes = array_keys($model->changes ?? []);
            $count = count(array_intersect(['deleted_at','name'],$changes));
            if ($count > 0) {
                $students = $model->school->students->sortBy('name');
                $order = 1;
                $students->transform(function ($q)use(&$order){
                    $q->order = $order;
                    $q->save();
                    ++$order;
                });
            }
        });

        self::saved(function($model){
            $changes = array_keys($model->changes ?? []);
            $count = count(array_intersect(['deleted_at','name'],$changes));
            if ($count > 0) {
                $students = $model->school->students->sortBy('name');
                $order = 1;
                $students->transform(function ($q)use(&$order){
                    $q->order = $order;
                    $q->save();
                    ++$order;
                });
            }
        });


        self::deleted(function($model){
            $students = $model->school->students->sortBy('name');
            $order = 1;
            $students->transform(function ($q)use(&$order){
                $q->order = $order;
                $q->save();
                ++$order;
            });
        });
    }

    public function school()
    {
        return $this->belongsTo(School::class);
    }
}

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\School;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class StudentController extends Controller
{
    public function show($id)
    {
        $data['school'] = $school = School::find($id);
        if (!$school) {
            return redirect('schools');
        }

        $data['students'] = $school->students()->paginate(5);
        return view('admin.students.index',$data);
    }

    public function edit($id)
    {
        $data['student'] = Student::find($id);
        $data['action'] = route('admin.students.update',$data['student']->id);
        $data['method'] = 'PUT';
        return view('admin.students.form',$data);
    }

    public function update($id,Request $request)
    {
        $validation = Validator::make($request->all(),[
            'name'=>'required'
        ]);

        if ($validation->fails()) {
            return back()->with('error',$validation->errors()->first());
        }

        $student = Student::find($id);

        $student->update([
            'name'=>$request->name,
            'status'=>$request->status == 'on'
        ]);
        return redirect(url()->previous())->with('success','Updated Successfully!');
    }

    public function create()
    {
        $data['action'] = route('admin.students.store');
        $data['schools'] = School::pluck('name','id');
        $data['method'] = 'POST';
        return view('admin.students.form',$data);
    }

    public function store(Request $request)
    {
        $validation = Validator::make($request->all(),[
            'name'=>'required',
            'school_id'=>'required|exists:schools,id'
        ]);

        if ($validation->fails()) {
            return redirect(url()->previous())->with('error',$validation->errors()->first());
        }
        Student::create([
            'name'=>$request->name,
            'status'=>$request->status == 'on',
            'school_id'=>$request->school_id
        ]);

        return redirect(url()->previous())->with('success','Created Successfully!');
    }

    
    public function destroy($id)
    {
        Student::find($id)->delete();
        return response()->json(['status'=>true]);
    }
}

app/Http/Controllers/Api/StudentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\SchoolCollection;
use App\Http\Resources\StudentCollection;
use App\Http\Resources\StudentResource;
use App\School;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class StudentController extends Controller
{
    public function show($id)
    {
        $school = School::find($id);
        if (!$school) {
            return response()->json('Page Not Found',404);
        }

        $students = $school->students()->paginate(10);
        return response()->json(new StudentCollection($students));
    }

    public function update($id,Request $request)
    {
        $validation = Validator::make($request->all(),[
            'name'=>'required',
            'school_id'=>'required|exists:schools,id'
        ]);

        if ($validation->fails()) {
            return response()->json(['msg'=>$validation->errors()->first()],422);
        }

        $student = Student::find($id);
        $student->update($request->only('name','status','school_id'));
        return response()->json(new StudentResource($student));
    }

    public function store(Request $request)
    {
        $validation = Validator::make($request->all(),[
            'name'=>'required',
            'school_id'=>'required|exists:schools,id'
        ]);

        if ($validation->fails()) {
            return response()->json(['msg'=>$validation->errors()->first()],422);
        }
        $student = Student::create([
            'name'=>$request->name,
            'status'=>$request->status??0,
            'school_id'=>$request->school_id
        ]);

        return response()->json(new StudentResource($student));
    }

    
    public function destroy($id)
    {
        $student = Student::find($id);
        if (!$student) {
            return response()->json('not found',404);
        }
        $student->delete();
        return response()->json(['status'=>true]);
    }

    public function schools()
    {
        $schools = School::paginate(10);
        return response()->json(new SchoolCollection($schools));
    }
}

resources/views/admin/students/form.blade.php
@extends('admin.layout')

@section('title',isset($student->id) ? "Update Student#".$student->id : 'Create Student')
@section('content')
<div class="row alert alert-primary">
    <a href="{{route('admin.students.show',request('school')??$student->school_id??'school')}}" class="btn btn-success">Back</a>
</div>
    <form action="{{$action}}" method="POST">
        @csrf
        @if ($method == 'PUT')
            @method('PUT')            
        @endif
        <div class="row">
            <div class="col-sm-6">
                <label for="name">Name :</label>
                <input type="text" name="name" class="form-control" value="{{isset($student) ? $student->name : ''}}">
            </div>
            @if (request('school'))
                <input type="hidden" name="school_id" value="{{request('school')}}">
            @elseif(isset($schools))
            <div class="col-sm-3">
                <label for="school_id">Select School</label>
                <select name="school_id" id="school_id" class="form-control">
                    @foreach ($schools as $id=>$name)
                        <option value="{{$id}}">{{$name}}</option>
                    @endforeach
                </select>
            </div>
            @endif
            <div class="form-check col-sm-3" style="margin-top: 26px" >
                <label for="flexCheckChecked">
                    Checked checkbox
                </label>
                <input  name="status" type="checkbox" id="flexCheckChecked" {{isset($student) && $student->status == 1 ? 'checked' : ''}}>
            </div>

            <button type="submit" class="col-sm-3 btn btn-info">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/students/index.blade.php
@extends('admin.layout')
@section('title','Students')


@section('content')
<div class="row alert alert-primary">
    <h1 class="text-center">
        School : {{$school->name}}
    </h1>
    <a href="{{route('admin.schools.index')}}" class="btn btn-success">Back</a>
</div>

<a href="{{route('admin.students.create',['school'=>$school->id])}}" class="btn btn-success">Create New Student</a>
<table class="table table-striped table-dark table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
        <th scope="col">OPS</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($students as $student)
        <tr>
            <th scope="row">{{$student->id}}</th>
            <td>{{$student->name}}</td>
            <td>{{$student->status == 1 ? 'ACTIVE' : "NOT ACTIVE"}}</td>
            <td>
              <a href="{{route('admin.students.edit',$student->id)}}" class="btn btn-info">Edit</a>
              <a href="javascript:" data-href="{{route('admin.students.destroy',$student->id)}}" class="btn btn-danger deleteBTN">Delete</a>
            </td>
          </tr>    
        @endforeach
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
  {!! $students->links() !!}
</div>
  
@endsection