routes/web.php
<?php

use App\School;
use App\Student;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/','schools');
Route::group(['as'=>'admin.','namespace'=>'Admin'],function(){
    Route::resource('schools','SchoolController');
    Route::resource('students','StudentController');
});

app/School.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $guarded = [];

    public function students()
    {
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/Admin/SchoolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\School;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SchoolController extends Controller
{
    public function index()
    {
        $data['schools'] = School::/*->withTrashed()*/paginate(5);
        return view('admin.schools.index',$data);
    }

    public function edit($id)
    {
        $data['school'] = School::find($id);
        $data['action'] = route('admin.schools.update',$data['school']->id);
        $data['method'] = 'PUT';
        return view('admin.schools.form',$data);
    }

    public function update($id,Request $request)
    {
        $validation = Validator::make($request->all(),[
            'name'=>'required'
        ]);

        if ($validation->fails()) {
            return back()->with('error',$validation->errors()->first());
        }

        $school = School::find($id);

        $school->update([
            'name'=>$request->name,
            'status'=>$request->status == 'on'
        ]);
        return back()->with('success','Updated Successfully!');
    }

    public function create()
    {
        $data['action'] = route('admin.schools.store');
        $data['method'] = 'POST';
        return view('admin.schools.form',$data);
    }

    public function store(Request $request)
    {
        $validation = Validator::make($request->all(),[
            'name'=>'required'
        ]);

        if ($validation->fails()) {
            return back()->with('error',$validation->errors()->first());
        }
        School::create([
            'name'=>$request->name,
            'status'=>$request->status == 'on'
        ]);

        return back()->with('success','Created Successfully!');
    }

    public function destroy($id)
    {
        School::find($id)->delete();
        return response()->json(['status'=>true]);
    }
}

resources/views/admin/schools/form.blade.php
@extends('admin.layout')

@section('title',isset($school->id) ? "Update School#".$school->id : 'Create School')
@section('content')
    <form action="{{$action}}" method="POST">
        @csrf
        @if ($method == 'PUT')
            @method('PUT')            
        @endif
        <div class="row">
            <div class="col-sm-6">
                <label for="name">Name :</label>
                <input type="text" name="name" class="form-control" value="{{isset($school) ? $school->name : ''}}">
            </div>
            <div class="form-check col-sm-3" style="margin-top: 26px" >
                <label for="flexCheckChecked">
                    Checked checkbox
                </label>
                <input  name="status" type="checkbox" id="flexCheckChecked" {{isset($school) && $school->status == 1 ? 'checked' : ''}}>
            </div>

            <button type="submit" class="col-sm-3 btn btn-info">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/schools/index.blade.php
@extends('admin.layout')
@section('title','Schools')


@section('content')
<a href="{{route('admin.schools.create')}}" class="btn btn-success">New School</a>
<table class="table table-striped table-dark table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
        <th scope="col">OPS</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($schools as $school)
        <tr>
            <th scope="row">{{$school->id}}</th>
            <td>{{$school->name}}</td>
            <td>{{$school->status == 1 ? 'ACTIVE' : "NOT ACTIVE"}}</td>
            <td>
                <a href="{{route('admin.schools.edit',$school->id)}}" class="btn btn-success">Update</a>
                <a href="javascript:" data-href="{{route('admin.schools.destroy',$school->id)}}" class="btn btn-danger deleteBTN">Delete</a>
                <a href="{{route('admin.students.show',$school->id)}}" class="btn btn-info">Show Students</a>
            </td>
          </tr>    
        @endforeach
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
  {!! $schools->links() !!}
  </div>
@endsection